spring.application.name=Blog_App


spring.datasource.url=jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a8f3d9c1b4e6f7a8d2c4b6e8f0a1c3d5e7f9a2b4c6d8e0f1a3b5c7d9e1f2a4
jwt.expiration=86400000


